//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnisaCake.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bahan_baku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bahan_baku()
        {
            this.bahan_baku_Masuk = new HashSet<bahan_baku_Masuk>();
            this.bahan_baku_keluar = new HashSet<bahan_baku_keluar>();
        }
    
        public int id_bahan_baku { get; set; }
        public string nama_bahan_baku { get; set; }
        public string satuan { get; set; }
        public Nullable<int> stok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahan_baku_Masuk> bahan_baku_Masuk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bahan_baku_keluar> bahan_baku_keluar { get; set; }
    }
}
