//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnisaCake.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesanan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pesanan()
        {
            this.transaksis = new HashSet<transaksi>();
        }
    
        public int id_pesanan { get; set; }
        public System.DateTime tgl_pesan { get; set; }
        public int id_pemesan { get; set; }
        public int id_kue { get; set; }
        public int id_size { get; set; }
        public int kode_toping { get; set; }
        public string deskripsi_pesanan { get; set; }
        public long jumlah_kue { get; set; }
        public long harga { get; set; }
        public string jenis_pembayaran { get; set; }
        public string jenis_pesanan { get; set; }
        public string jenis_pengambilan { get; set; }
    
        public virtual kue kue { get; set; }
        public virtual pelanggan pelanggan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaksi> transaksis { get; set; }
        public virtual ukuran_kue ukuran_kue { get; set; }
        public virtual toping toping { get; set; }
    }
}
