//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnisaCake.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SI_TKueEntities : DbContext
    {
        public SI_TKueEntities()
            : base("name=SI_TKueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<kranjang> kranjangs { get; set; }
        public virtual DbSet<kue> kues { get; set; }
        public virtual DbSet<pelanggan> pelanggans { get; set; }
        public virtual DbSet<pesanan> pesanans { get; set; }
        public virtual DbSet<toping> topings { get; set; }
        public virtual DbSet<transaksi> transaksis { get; set; }
        public virtual DbSet<ukuran_kue> ukuran_kue { get; set; }
        public virtual DbSet<bahan_baku> bahan_baku { get; set; }
        public virtual DbSet<bahan_baku_keluar> bahan_baku_keluar { get; set; }
        public virtual DbSet<bahan_baku_Masuk> bahan_baku_Masuk { get; set; }
    
        public virtual ObjectResult<GetCategory_Result> GetCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategory_Result>("GetCategory");
        }
    
        public virtual ObjectResult<SP_GetAllKue_Result> SP_GetAllKue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllKue_Result>("SP_GetAllKue");
        }
    
        public virtual ObjectResult<string> SP_SelectCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SelectCategory");
        }
    }
}
