//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnisaCake.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_menu_tree
    {
        public int id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string icon { get; set; }
        public string parent { get; set; }
        public Nullable<int> order_by { get; set; }
        public string role { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
