//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnisaCake.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id_user { get; set; }
        public string nama_user { get; set; }
        public string alamat { get; set; }
        public string no_hp { get; set; }
        public string email { get; set; }
        public Nullable<int> id_role { get; set; }
        public string sandi { get; set; }
    }
}
